const actionTypes = {
  LOAD_FILMS: `LOAD_FILMS`,
  LOAD_PROMO: `LOAD_PROMO`,
  LOAD_FAVORITE: `LOAD_FAVORITE`,
  SET_CURRENT: `SET_CURRENT`,
  LOAD_CURRENT: `LOAD_CURRENT`,
  UPDATE_FAVORITE: `UPDATE_FAVORITE`,
  SELECT_GENRE: `SELECT_GENRE`,
  GET_GENRES: `GET_GENRES`,
  RESET_GENRES: `RESET_GENRES`,
  PREPARE_FILMS: `PREPARE_FILMS`,
  MANAGE_LIST: `MANAGE_LIST`,
  SET_VISIBLE_FILMS: `SET_VISIBLE_FILMS`,
  LOAD_COMMENTS: `LOAD_COMMENTS`,
  ADD_COMMENT: `ADD_COMMENT`,
};

export default actionTypes;
